approvals:
  groups:
    - name: 'Lightning Apps'
      minimum: 1
      from:
        - alecmerdler
        - awaelchli
        - hhsecond
        - lantiga
        - manskx
        - nohalon
        - tchaton
